
-- 7 SQL Questions:

1.Identify the top 5 doctors who generated the most revenue but had the fewest patients. (SQL)

SELECT 
    `Doctor Name`,
    SUM(`Total Bill`) AS total_revenue,
    COUNT(DISTINCT patient_id) AS patient_count
FROM doctor_pateints_data
GROUP BY `Doctor Name`
ORDER BY patient_count ASC,total_revenue DESC
LIMIT 5;

2.	Find the department where the average waiting time has decreased over three consecutive months. (SQL)

WITH monthly_avg AS (
    SELECT 
        department_referral,
        DATE_FORMAT(STR_TO_DATE(date, '%d-%m-%Y'), '%Y-%m') AS month,
        AVG(patient_waittime) AS avg_wait
    FROM hospital_er
    GROUP BY department_referral, month
),
lagged AS (
    SELECT 
        department_referral,
        month,
        avg_wait,
        LAG(avg_wait,1) OVER (PARTITION BY department_referral ORDER BY month) AS prev1_avg_wait,
        LAG(avg_wait,2) OVER (PARTITION BY department_referral ORDER BY month) AS prev2_avg_wait,
        LAG(month,1) OVER (PARTITION BY department_referral ORDER BY month) AS prev1_month,
        LAG(month,2) OVER (PARTITION BY department_referral ORDER BY month) AS prev2_month
    FROM monthly_avg
)
SELECT 
    department_referral,
    prev2_month,
    prev1_month,
    month AS current_month,
    prev2_avg_wait,
    prev1_avg_wait,
    avg_wait
FROM lagged
WHERE avg_wait < prev1_avg_wait 
  AND prev1_avg_wait < prev2_avg_wait;
  
  
3.	Determine the ratio of male to female patients for each doctor and rank the doctors based on this ratio. (SQL)

SELECT 
    dp.`Doctor Name`,
    SUM(CASE WHEN he.patient_gender = 'M' THEN 1 ELSE 0 END) AS male_count,
    SUM(CASE WHEN he.patient_gender = 'F' THEN 1 ELSE 0 END) AS female_count,
    SUM(CASE WHEN he.patient_gender = 'M' THEN 1 ELSE 0 END) /
    NULLIF(SUM(CASE WHEN he.patient_gender = 'F' THEN 1 ELSE 0 END), 0) AS male_female_ratio,
    RANK() OVER (
        ORDER BY 
        SUM(CASE WHEN he.patient_gender = 'M' THEN 1 ELSE 0 END) /
        NULLIF(SUM(CASE WHEN he.patient_gender = 'F' THEN 1 ELSE 0 END), 0) DESC
    ) AS rank_doctor
FROM doctor_pateints_data dp
JOIN hospital_er he ON dp.patient_id = he.patient_id
GROUP BY dp.`Doctor Name`;

4. 	Calculate the average satisfaction score of patients for each doctor based on their visits. (SQL)

SELECT 
    d.`Doctor Name`,
    ROUND(AVG(CASE 
                WHEN h.patient_sat_score = '' OR h.patient_sat_score IS NULL THEN 5
                ELSE CAST(h.patient_sat_score AS DECIMAL(5,2))
            END), 2
    ) AS avg_satisfaction_score
FROM hospital_er h
INNER JOIN doctor_pateints_data d
    ON d.patient_id = h.patient_id
GROUP BY d.`Doctor Name`
ORDER BY avg_satisfaction_score DESC;

5.  Find doctors who have treated patients from different races and calculate the diversity of their patient base. (SQL)

SELECT 
    d.`Doctor Name`,
    COUNT(DISTINCT h.patient_race) AS unique_races,
    COUNT(DISTINCT h.patient_id) AS total_patients,
    ROUND(
        COUNT(DISTINCT h.patient_race) / COUNT(DISTINCT h.patient_id), 4
    ) AS diversity_ratio
FROM hospital_er h
INNER JOIN doctor_pateints_data d
    ON h.patient_id = d.patient_id
GROUP BY d.`Doctor Name`
HAVING COUNT(DISTINCT h.patient_race) > 1
ORDER BY diversity_ratio DESC;


6.	Calculate the ratio of total bills generated by male patients to female patients for each department. (SQL)

SELECT 
    d.department_referral,
    SUM(CASE WHEN h.patient_gender = 'M' THEN d.`Total Bill` ELSE 0 END) AS male_revenue,
    SUM(CASE WHEN h.patient_gender = 'F' THEN d.`Total Bill` ELSE 0 END) AS female_revenue,
    ROUND(
        SUM(CASE WHEN h.patient_gender = 'M' THEN d.`Total Bill` ELSE 0 END) /
        NULLIF(SUM(CASE WHEN h.patient_gender = 'F' THEN d.`Total Bill` ELSE 0 END), 0), 4) AS male_female_revenue_ratio
FROM doctor_pateints_data d
JOIN hospital_er h 
    ON d.patient_id = h.patient_id
GROUP BY d.department_referral;

7.	Update the patient satisfaction score for all patients who visited the "General Practice" department and 
    had a waiting time of more than 30 minutes. 
    Increase their satisfaction score by 2 points, but ensure that the satisfaction score does not exceed 10. (SQL)
    
SET SQL_SAFE_UPDATES = 0;
UPDATE hospital_er
SET patient_sat_score = 
    LEAST(CASE 
            WHEN patient_sat_score = '' OR patient_sat_score IS NULL THEN 2
            ELSE CAST(patient_sat_score AS SIGNED) + 2
        END,10)
WHERE department_referral = 'General Practice'
  AND patient_waittime > 30;
SET SQL_SAFE_UPDATES = 1;